baseurl = "https://pages.git.target.com/target-chatops/chatops-docs"
title = "Target + Slack"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Target"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/avatar.jpg"
    favicon_16 = "/images/avatar.jpg"

    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]
